# Generated by Django 4.2.7 on 2023-11-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='progile_img',
            new_name='profile_img',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=300, null=True),
        ),
    ]
