# Generated by Django 4.2.7 on 2023-11-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_progile_img_user_profile_img_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='media/user.png', upload_to=''),
        ),
    ]
