# Generated by Django 4.2.7 on 2023-11-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='desire_amount_deposit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='desire_amount_saving',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
