# Generated by Django 4.2.7 on 2023-11-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_desire_amount_deposit_user_desire_amount_saving'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deposit_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='saving_period',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
